name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build Project
        run: |
          # ساخت پروژه تمیز و استاندارد
          flutter create release_app --org com.shohadaamameh.heyat
          cd release_app

          # نصب خودکار بسته‌ها بدون تداخل نسخه
          flutter pub add flutter_localizations --sdk=flutter
          flutter pub add intl http shared_preferences url_launcher

          # جایگذاری کد اختصاصی هیئت
          cp $GITHUB_WORKSPACE/lib/main.dart lib/main.dart

          # ساخت مستقیم APK
          flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Heyat-App-Release
          path: release_app/build/app/outputs/flutter-apk/app-release.apk
